import type { Metadata } from "next";
import { Exo, Noto_Sans_JP } from "next/font/google";
import InitialLoader from "@/components/InitialLoader";
import "./globals.css";

const exo = Exo({
  variable: "--font-exo",
  subsets: ["latin"],
});

const notoSansJP = Noto_Sans_JP({
  variable: "--font-noto-sans-jp",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head>
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons+Round"
          rel="stylesheet"
        />
      </head>
      <body className={`${exo.variable} ${notoSansJP.variable} antialiased`}>
        <InitialLoader />
        {children}
      </body>
    </html>
  );
}
